
export const keywords = {

    customerService: [
        '1',
        '1️⃣',
        'atencion al cliente',
        'asesor',
        'ayuda',
        'dudas',
        'soporte',
        'consultas',
        'asistencia',
        'informacion',
        'consultar',
        'servicio al cliente',
      ],
      creditRequest: [
        '2',
        '2️⃣',
        'solicitar',
        'prestamo',
        'credito',
        'solicitud',
        'financiamiento',
        'aprobacion',
        'crediticio',
        'financiero',
        'aumento',
      ],
      walletArea: [
        '3',
        '3️⃣',
        'cartera',
        'asesor',
        'asesor cartera',
        'cartera de clientes',
        'gestión de cartera',
        'cuentas',
        'recaudación',
        'administración de cartera',
        'juridica',
        'embargado',
        'paz y salvo',
      ],
      accounting: [
        '4',
        '4️⃣',
        'contabilidad',
        'contable',
        'contas',
        'finanzas',
        'libros contables',
        'informes contables',
        'balanza',
        'registros contables',
        'retiro',
      ],
}